### ISSUE TITLE
Potential issues in feature extractor

### ISSUE THREAD

**Issue by ozancaglayan** [guillaumekln/faster-whisper#201]
Hi.

Correct if I'm wrong but I think the below code piece makes sure that the input is 30 seconds long (if not already) if `padding=True`. However, the way `np.pad` is called will always add `self.n_samples` more zeros on the right side rather than padding it to `self.n_samples`, e.g. if the waveform has 20 seconds of content, this call will extend it to 50 seconds and probably extract features from bunch of zero padded windows.

https://github.com/guillaumekln/faster-whisper/blob/d889345e071de21a83bdae60ba4b07110cfd0696/faster_whisper/feature_extractor.py#L151

Another one:
https://github.com/guillaumekln/faster-whisper/blob/d889345e071de21a83bdae60ba4b07110cfd0696/faster_whisper/feature_extractor.py#L107

Here `frame_width` will be more or less `n_fft` whereas `waveform.shape[0]` is often quite larger than `n_fft`.  The right hand side of the expression should probably be `self.n_fft` seen the amount of padding applied in the following lines?

**Comment by guillaumekln** [comment]
Hi,

The first padding is correct. It is done this way so that every positions in the original audio are followed by at least 30 seconds of features. See also the reference implementation:

https://github.com/openai/whisper/blob/919a713499d4c4f76ecf448617ada8e9ac008fbb/whisper/audio.py#L135-L136

For the second padding you may be right. Since this code is coming from Transformers, can you first open an issue there?

https://github.com/huggingface/transformers/blob/v4.28.1/src/transformers/models/whisper/feature_extraction_whisper.py

**Comment by ozancaglayan** [comment]
Hi thanks! I see now that the first one is kind of a deliberate choice but it is still counter-intuitive to me why we first pad with 30 seconds silence, get the features and then eventually use only the features from the actual signal by slicing later. From what I understand, the logic here is to be able to slide over the input in the transcribe function in 3000-sized chunks in a way?

Thanks!

**Comment by guillaumekln** [comment]
> then eventually use only the features from the actual signal by slicing later

That’s not what is happening during the transcription. The slicing always returns 30-second segments (with dimension 3000 as you mentioned). This is what is expected by the Whisper model.
