### ISSUE TITLE
Danger CVE-2021-29063 REDOS (Reg Exp Denial of Service) after pip install faster-whister on docker

### ISSUE THREAD

**Issue by marvin46** [guillaumekln/faster-whisper#257]
Hello @guillaumekln @jordimas @ozancaglayan @tekacs @mayeaux 
My name is marvin

i'm on Reasearch on Faster Whisper usage, but after i'm RUN pip install -r requirements.txt on my docker image

my requirement.txt is here: (https://github.com/marvin46/vtt_fw/blob/main/requirements.txt)

the **CVE-2021-29063 REDOS (Regular expression Denial of Service)** is show after i scan my image
here the link : (https://dso.docker.com/cve/CVE-2021-29063)

you can pull my image on your docker desktop with this comman below: 
**docker pull marvinhris/vtt_fw:latest**

and scan with docker scout 

please fix this security issue

**Comment by guillaumekln** [comment]
Hi,

I'm not sure the warning is correct.

The CVE page indicates that the issue is fixed in `mpmath==1.3.0` and this version is installed in your Docker image.

**Comment by cdupuis** [comment]
Thanks for bringing this to our attention. The underlying is reason the advisory in https://github.com/pypa/advisory-database/blob/main/vulns/mpmath/PYSEC-2021-427.yaml#L17 which is missing the fix version. We've fixed this on our end so that this CVE should not get flagged any longer in Docker Scout. 

Thanks again and sorry for the noise.
