### ISSUE TITLE
CUDA 12 support (libcublas.so.11 is not found) 

### ISSUE THREAD

**Issue by digitalsignalperson** [guillaumekln/faster-whisper#263]
FYI on arch linux with the latest cuda 12.1.1-3 faster-whisper fails with `RuntimeError: Library libcublas.so.11 is not found or cannot be loaded` here:
https://github.com/guillaumekln/faster-whisper/blob/1bb7e33b933dde488a17fd556a1114ee0d58d34b/faster_whisper/transcribe.py#L564

Assuming it's a CTranslate2 problem I opened an issue here https://github.com/OpenNMT/CTranslate2/issues/1250

**Comment by g588928812** [comment]
you have to recompile CTranslate2, see [how to](https://github.com/OpenNMT/CTranslate2/blob/master/docs/installation.md)

took me an hour but works beautifully now, CUDA Version: 12.1

**Comment by guillaumekln** [comment]
Here the documentation is correct and says that CUDA 11.x should be installed: https://github.com/guillaumekln/faster-whisper#installation

On the other hand, the CTranslate2 documentation is misleading since the release of CUDA 12. I'm closing this issue in favor of the one you opened in the CTranslate2 repository.

**Comment by makoto-toyouke** [comment]
I have encountered an issue where Google Colab's CUDA version has been updated from 11 to 12, which is causing significant problems for me. Unfortunately, I have been unable to find a way to revert Colab back to CUDA 11 despite multiple attempts and research. I am currently facing difficulties due to this update. If possible, I would greatly appreciate any guidance on how to switch back to CUDA 11. However, if that's not feasible, I kindly request assistance in making my code compatible with CUDA 12.

**Comment by MissingTwins** [comment]
Official compilation guide is a mess, compilation for cuda 12 please refer to  [This](https://github.com/OpenNMT/CTranslate2/issues/1250#issuecomment-1913905422)

A quick fix without needing recompilation.
Change `/home/user/Notebook/fast-whisper/site-packages-gpu/` to your true `site-packages` folder
```
ln -s /usr/local/cuda/lib64/libcublas.so.12 /home/user/Notebook/fast-whisper/site-packages-gpu/nvidia/cublas/lib/libcublas.so.11
```
Original post please refer to [This](https://github.com/OpenNMT/CTranslate2/issues/1250#issuecomment-1936533861)
