### ISSUE TITLE
Different transcription with word_timestamps

### ISSUE THREAD

**Issue by Purfview** [guillaumekln/faster-whisper#280]
Is it normal that with `word_timestamps=True` transcription is different?
Like some words are transcribed differently or some words/sentences missing?

**Comment by guillaumekln** [comment]
Yes the transcription can be different because the segment boundaries are updated when enabling the word timestamps.

See for example https://github.com/openai/whisper/pull/1114 where some words are lost at the beginning of a segment (Example 3).

We applied the same fix in https://github.com/guillaumekln/faster-whisper/pull/226 but I wanted to wait for a new release of openai-whisper before merging it.

**Comment by Purfview** [comment]
Actually I use that #226 PR, it helps with timestamp's accuracy, but I didn't noticed it making impact on transcription.

Here missing "Yes" in a middle of  a segment [no word_timestamps vs word_timestamps]:

![alt text](https://i.imgur.com/iB0aND2.png)

Audio: https://we.tl/t-WZDr2Z31xB

Settings: `--device=cpu --model=medium --compute_type=int8 --beam_size=1`
