### ISSUE TITLE
Interrupted Word and punctuations

### ISSUE THREAD

**Issue by SunHaoRanCN** [guillaumekln/faster-whisper#319]
Hi, I am using faster-whisper for speech transcription.
As I want to detect interrupted words like 'uh' or 'um' in the speech, but when I provide an audio file, here is the output:
"[0.00s -> 17.00s]  if capturing interrupted words and specific disfluencies is crucial for your application."
The real transcription that I want should be like:
"um if capturing uh interrupted words and specific disfluencies is um crucial..."
Is there anything I can do to specify the granularity of transcription?

Besides, Is it possible to ignore punctuation?

**Comment by guillaumekln** [comment]
These words are typically not included in the training data that's why the model tends to ignore them. This is also mentioned in the OpenAI Whisper API:

> The model may also leave out common filler words in the audio. If you want to keep the filler words in your transcript, you can use a prompt that contains them: "Umm, let me think like, hmm... Okay, here's what I'm, like, thinking."

https://platform.openai.com/docs/guides/speech-to-text/prompting

The prompt can be set with the argument `initial_prompt` but I don't know if it actually works.

---

If you know the ID of the punctuation tokens to disable, you can ignore them like this:

```python
segments, info = model.transcribe(audio_path, suppress_tokens=[-1, 11, 13])
```

The token IDs can be found in previously generated segments for example (`segment.tokens`).
