### ISSUE TITLE
"Processing segment at..." logger is incorrect when VAD is enabled

### ISSUE THREAD

**Issue by Purfview** [guillaumekln/faster-whisper#377]
Can it be made to show correct timings?

**Comment by guillaumekln** [comment]
This part of the code does not know that silences were removed from the input audio. I'd like to keep it that way.

Otherwise you have to map the times which makes the code more complex. Not worth it for debug logs. It would also be misleading since the 30-second segments in the "cleaned" audio does not necessarily correspond 30 contiguous seconds in the original audio.
