### ISSUE TITLE
Memory Leak investigation

### ISSUE THREAD

**Issue by adambuar** [guillaumekln/faster-whisper#390]
Hi, first off - thank you very much for sharing this! This is super helpful.
I've been putting this model to work on AWS Sagemaker for about a week now on multiple instances - and every few hours i see the memory of an instance is maxed out and the worker is killed. see graph:
<img width="1743" alt="Screenshot 2023-07-31 at 9 57 05" src="https://github.com/guillaumekln/faster-whisper/assets/8166910/2429ad0a-6e64-4e40-baf6-0c4f413a19ae">

This is what i'm seeing in Sagemaker logs for each drop you see in the memory graph(screenshot):

"[ERROR] Worker (pid:25) was sent SIGKILL! Perhaps out of memory?"

I've been able to recreate this on an EC2 machine running CUDA
i am using **ml.g4dn.xlarge** instance type python 3.10 and CUDA 11

This is the code i am using for the transcription:

`self.model = WhisperModel("small", device="cuda")

segments, _ = self.model.transcribe(audio=audio_bytes, language="en", initial_prompt=initial_prompt,
                                            no_speech_threshold=0.2)
        transcript_text = ''.join([segment.text for segment in segments])`
        
*I am initializing the model once upon instance deployment

Would appreciate any assistance with this issue - the performance is amazing!

Thanks in advance

**Comment by guillaumekln** [comment]
Hi,

How do you know that the memory is used by faster-whisper? Can you share a standalone code snippet to reproduce the issue?

I just tried the transcription of a 1-hour audio file on the GPU and the system memory usage was constant all along.

**Comment by adambuar** [comment]
Hi, thank you for the quick reply! 
Here is a simple function i defined to recreate the issue:

`if __name__ == '__main__':
    model = WhisperModel("small", device="CUDA")
    while True:
        segments, _ = model.transcribe(audio="audio.mp3",
                                        language="en", initial_prompt="""This is a transcript of an audio file.""",
                                        no_speech_threshold=0.2)
        transcript_text = ''.join([segment.text for segment in segments])
        print(f"text{transcript_text}")
`
The audio file is ~ 4.5 MB in size and about 9 mins long
it takes a quite a few hours to reach maximum memory (using 16GB of ram)
but it's possible to see a steady  increase in memory usage by the process over a few mins: see screenshots - these were taken right now from the currently running test

![Screenshot 2023-07-31 at 16 15 29](https://github.com/guillaumekln/faster-whisper/assets/8166910/54365c23-4a1f-4ded-a358-7ced37800eb1)
![Screenshot 2023-07-31 at 16 19 09](https://github.com/guillaumekln/faster-whisper/assets/8166910/29142a1c-df9c-444c-9c61-04cab68d7367)

Appreciate the help!!

**Comment by guillaumekln** [comment]
I think I reproduced this increasing memory usage. It looks related to the audio decoding. Forcing the garbage collector to run after each transcription seems to be a possible solution, but I will check if there is another way to fix this issue.

Here is the code I was using:

```python
import psutil
import gc
import sys
import faster_whisper

model = faster_whisper.WhisperModel("small", device="cuda", compute_type="int8")
audio_path = sys.argv[1]
process = psutil.Process()


def monitor_memory(audio, n=40, collect=False):
    for _ in range(n):
        segments, _ = model.transcribe(audio)
        text = "".join(segment.text for segment in segments)

        if collect:
            gc.collect()

        print(process.memory_info().rss / 1000000)

    print("")
    gc.collect()


print("Baseline")
monitor_memory(audio_path)

print("Run gc")
monitor_memory(audio_path, collect=True)

print("Decode audio once")
monitor_memory(faster_whisper.decode_audio(audio_path))
```

And here is an output I got. Note that the memory usage is completely flat when decoding the audio file once, even without forcing the GC to run.

```
Baseline
1430.97856
1431.109632
1431.371776
1431.63392
1431.63392
1431.63392
1431.63392
1431.764992
1439.698944
1452.818432
1472.69632
1490.194432
1512.93952
1533.038592
1551.941632
1574.223872
1594.605568
1534.357504
1534.357504
1534.357504
1534.357504
1534.357504
1534.357504
1534.357504
1534.488576
1534.619648
1534.619648
1534.75072
1534.881792
1535.012864
1554.427904
1573.093376
1572.560896
1572.560896
1572.429824
1572.298752
1572.298752
1572.298752
1572.429824
1572.560896

Run gc
1488.09728
1488.09728
1488.09728
1488.09728
1488.09728
1487.966208
1488.09728
1488.09728
1487.966208
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.966208
1487.966208
1487.966208
1487.966208
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.966208
1487.966208
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.835136
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968

Decode audio once
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
1487.699968
```

**Comment by Lorenzoncina** [comment]
Hello! I'd like to report a behaviour I'm noticing on this issue too. 

I'm transcribing an audio file of 3 hours (so, pretty long) using Whisper Large V2 (both the pre-trained and a fine-tuned version I trained with in-domain data).
I'm noticing that the GPU memory usage not only is not constant , but it has some peaks which **leads to the necessity to have more free memory** on the GPU which runs the model. In my case this is pretty anoying because the GPU is shared among multiple process, so It would be nice to have a nearly flat GPU memory usage by Faster Whisper.

This is what I'm currently experiencing with both **Large V2** models using **float 16 quantization**:
max GPU meory usage: around 5900MB. This value is a peak, and is higher than the average value which is lower than 5GB, so closer to the value reported on the main page of this repository (4755MB). I tried using int 8 quantization but it seems to work only on certain GPU, on others it doesnt work, so I can't reduce this value by changing quantization, so I'mtrying at least to make it constant without peaks like in this case.

I report here the log of **max GPU usage** monitored during the inference of this long audio file with faster-whisper Larg v2:
3302
3582
3888
4294
4390
4454
4550
4582
4678
4710
4806
4870
4902
4966
5030
5062
5094
5702
5734
5798

Bash script  used to monitor this max GPU memory usage:

`a=0
while true; do
  b=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits | awk '{print $1}')
  if [ "$b" -gt "$a" ]; then
    a=$b
    echo "$a"
  fi
  sleep 0.5
done
`

I tried to use the Gargabe collector trick you proposed in the previous comment but it doesn't change the memory usage.
It's also important to underline that same models runned with Hugging Face API show a more constant GPU memory Usage (altough of course it's way higher then faster-whisper)

Do you have any idea if it's possibile to make the GPU memory usage constant and avoid these peaks?

**Comment by bakermanbrian** [comment]
I would like to report this same issue -- hard to reproduce, but seeing it consistently on my containerized faster whisper application

<img width="1363" alt="Screenshot 2024-02-04 at 7 37 40 PM" src="https://github.com/SYSTRAN/faster-whisper/assets/111606171/504c4605-5c78-40c9-91d6-10384c95cf96">

**Comment by wojnicki** [comment]
The leak on cpu is huge. Here is an example on 1 minute wav file.
``` python
import gc
import psutil

model_size = "small"

def f():
    from faster_whisper import WhisperModel, BatchedInferencePipeline
    model = WhisperModel(model_size, device="cpu", compute_type="int8")

    batched_model = BatchedInferencePipeline(model=model)
    segments, info = batched_model.transcribe("audio.wav", batch_size=8, language="pl",
                                              )

    for segment in segments:
        # these iterations cause the most of memory leak
        # print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
        gc.collect()
    return()

for i in range(10):
    f()
    gc.collect()
    process = psutil.Process()
    print(process.memory_info().rss/1000000)
```
And the results:
855.781376
817.963008
869.13024
935.600128
1181.069312
1116.409856
1181.30688
1363.345408
1238.831104
1120.54272
