### ISSUE TITLE
What are the minimum requirements to run faster whisper locally?

### ISSUE THREAD

**Issue by heloisypr** [guillaumekln/faster-whisper#556]
I want to run it locally but I don't know if my machine can do it. I would like to know the requirements for each version of whisper

**Comment by Juergen-J-F** [comment]
For GPU, you need a CUDA enabled GPU, for some (esp. older), you will have to use int8 instead of float16. For CPU, there does not really seem to be a lower limit that we found, it just takes longer. Only limit might be memory, but faster-whisper states around 3GB of ram use for the large v2 model. For the effect of transcription times with different model sizes on different CPUs we have a small comparison in our repository: https://github.com/BANDAS-Center/aTrain#benchmarks. If you just want to test it quickly to see if it works, you can use our GUI setup in the same repository, or if you use windows install it from the microsoft store: https://apps.microsoft.com/detail/atrain/9N15Q44SZNS2. 

Hope this helps a little.

**Comment by Purfview** [comment]
> I want to run it locally but I don't know if my machine can do it.

If your machine is not older than ~13 years then it should run it.

**Comment by lamoboos223** [comment]
is it possible to run the faster whisper on pi and be efficient? @JuergenFleiss

**Comment by JuergenFleiss** [comment]
> is it possible to run the faster whisper on pi and be efficient? @JuergenFleiss

No idea, you would have to try. You probably want one of the larger ram models though.

**Comment by sdsmith** [comment]
@lamoboos223 did you run any experiments? What were the results?
