### ISSUE TITLE
How should I debug incorrect transcription ?

### ISSUE THREAD

**Issue by junchen6072** [guillaumekln/faster-whisper#86]
Sorry I can't share my audio, but sometimes it could have extra words not in the audio.  In this case, there're some phrases repeatedly happening. Sometimes it'll also missing numbers or a repetitive sentence(two short sentences that are same).
Wondering how usually people debug such issue. Any suggestions?

**Comment by phineas-pta** [comment]
it's the hallucination problem, read more about it here: openai/whisper#679

you'll have to play with the options to see which works for you:
 - use `medium` instead of `large-v2`, in my experience sometimes `medium` is better
 - enable SileroVAD, also the parameters
 - set `condition_on_previous_text` to False
